const qList = {
    '1':	'What is your favorite sleeping position of all time?',
    '2':	'What is the dumbest way you have been hurt?',
    '3':	'What are the three scents you like?',
    '4':	'What sport will be invented next?',
    '5':	'What’s your favorite board game?',
    '6':	'Which word would you use if you could only use one for the rest of your life?',
    '7':	'Would you rather have intelligence over looks?',
    '8':	'What’s your most embarrassing moment in grade school?',
    '9':	'Would you rather stay in or go out on a Friday night?',
    '10':	'Have you ever thrown someone an extravagant party?',
    '11':	'What is the weirdest thing you have ever eaten?',
    '12':	'Out of the four seasons, what’s your favorite one?',
    '13':	'What is the most absurd thing you have been tricked into doing or believing?',
    '14':	'What is something that’s true that nobody agrees with you on?',
    '15':	'Which instrument has the funniest sound?',
    '16':	'Where would you relocate if you were forced to leave the country?',
    '17':	'Do you care about what other people tell you?',
    '18':	'If you could meet anyone in this world today, who would you meet?',
    '19':	'What’s the best type of cheese for you?',
    '20':	'What is the greatest risk you have ever taken?',
    '21':	'Have you ever thought of what your future baby will be named?',
    '22':	'What are those things you are too old to do but you still enjoy?',
    '23':	'What are your pet peeves?',
    '24':	'Who’s the messiest person you’ve ever known?',
    '25':	'Which of the two smells better, fresh-cut grass or bread baking in the oven?',
    '26':	'Who is your all-time favorite Disney character?',
    '27':	'Are you afraid of ghosts?',
    '28':	'Can you carry an elephant?',
    '29':	'What’s the worst color that was ever invented?',
    '30':	'What is the weirdest text you have ever received recently?',
    '31':	'What would you be if you had to wear one Halloween costume every day for the rest of your life?',
    '32':	'What is one ability that you believe everybody should possess?',
    '33':	'How many times has your heart been broken?',
    '34':	'What is the first thing you do after getting home from a trip?',
    '35':	'What are the things you’d spend with a billion dollars?',
    '36':	'What are the songs that make you sing along whenever you hear it?',
    '37':	'How did your parents meet?',
    '38':	'What has been your greatest kitchen mistake?',
    '39':	'What is the craziest bet you have ever made?',
    '40':	'Do you believe that love is blind?',
    '41':	'Who would you want to trade lives with?',
    '42':	'If you were given the chance to steal something, what would it be?',
    '43':	'What type of cuisine would you serve your customers if you own a five-star restaurant?',
    '44':	'What is the fanciest event you have ever attended?',
    '45':	'Who is your greatest enemy?',
    '46':	'What food should taste better than its appearance?',
    '47':	'What’s the first thing you pack during an out of the country flight?',
    '48':	'Do you actively post on social media?',
    '49':	'If you could only teach three things to your future child, what would it be?',
    '50':	'What is the worst TV advertisement you’ve seen recently?',
    '51':	'What’s the most addictive game for you?',
    '52':	'What do you usually do during weekends?',
    '53':	'If you were given the chance to make your one wish come true, what would it be?',
    '54':	'What period would you travel to if you were given a time machine?',
    '55':	'What’s the food you usually refuse to share?',
    '56':	'What are the hobbies you want to develop?',
    '57':	'Do you believe in horoscopes?',
    '58':	'What was your favorite childhood book?',
    '59':	'Would you take it if you had the opportunity to be immortal?',
    '60':	'What is something your brain wants to convince you to do but you have to fight it?', 
    '61':	'Which would be the smartest animal if they could all talk?',
    '62':	'What movie makes you laugh even after watching it several times?',
    '63':	'What’s your favorite toy when you were a child?',
    '64':	'What is the best name you could think for a cat?',
    '65':	'Have you ever counted your steps while walking?',
    '66':	'Do you believe in heaven?',
    '67':	'If you have a million, what are the things you wouldn’t spend?',
    '68':	'If you could have lunch with one person from history, who would it be?',
    '69':	'What’s the certain product you couldn’t live without?',
    '70':	'What would you name your yacht if you had one?',
    '71':	'Where is your all-time dream vacation?',
    '72':	'How do you want to die?',
    '73':	'What is the most stupid thing you’ve done in your entire life?',
    '74':	'If you could sit next to a famous celebrity in a restaurant, who would it be?',
    '75':	'If you had 24 hours to do whatever you wanted in this country, what would you like to do?',
    '76':	'If you could be a Hollywood celebrity, who would you like to become?',
    '77':	'What is your main reason for getting out of bed every day?',
    '78':	'How could you politely end a conversation with a person who is so annoying?',
    '79':	'What makes your day better?',
    '80':	'What is the strangest thing your teacher has ever done?',
    '81':	'What is the best color in the rainbow?',
    '82':	'Who is the best movie villain?',
    '83':	'Would you rather have 20 hobbies or a single passion?',
    '84':	'What’s your favorite exotic animal?',
    '85':	'How would you describe me based on my outside appearance?',
    '86':	'What is your favorite viral video?',
    '87':	'Who is your favorite YouTube vlogger?',
    '88':	'If you could only drink coffee or tea for the rest of your life, which one would you choose?',
    '89':	'What’s your favorite action movie?',
    '90':	'What gets you motivated?', 
    '91':	'What’s the most beautiful country you’ve ever visited?',
    '92':	'Would you rather cook or eat at a restaurant?',
    '93':	'What is the most useless talent you possess?',
    '94':	'What is the craziest thing you’ve done in school?',
    '95':	'How often do you replace your bedsheets?',
    '96':	'Do you like listening to podcasts?',
    '97':	'Do you like to save more or spend more?',
    '98':	'What is the weirdest superstition you’ve ever heard?',
    '99':	'If dark chocolate is the only available food in this planet, would you eat it?',
    '100':	'What are the two things you’d like to ask your pet?',
    '101':	'What’s the easiest dish to cook?',
    '102':	'If you could be any type of object, what would you like to be?',
    '103':	'How do you deal with a stressful environment?',
    '104':	'Which part of the roller coaster do you usually ride: the front, middle or back?',
    '105':	'What quotes do people admire but you think is a total lie?',
    '106':	'Do you believe in second chances?',
    '107':	'What has been the most flattering compliment you have ever received?',
    '108':	'Have you tried flirting with a stranger online?',
    '109':	'What would you like to change in this country if you were chosen as the president?',
    '110':	'Do you have a close relationship with your parents?',
    '111':	'What has been your hardest goodbye in life been so far?',
    '112':	'If you could change your name for a day, what would it be?',
    '113':	'Would you rather have a massage or get a facial?',
    '114':	'Can you describe to me your relationship with your dad?',
    '115':	'Which do you listen to the most: your heart or your brain?',
    '116':	'What would you do if you were offered a one-minute ad slot during the Super Bowl that you could not sell?',
    '117':	'When was the last time you’ve felt your biggest adrenaline rush?',
    '118':	'Who is the tallest member of your family?',
    '119':	'What traits did you get from your parents?',
    '120':	'Who do you look up to the most?',
    '121':	'Can you show me your oldest item inside your closet?',
    '122':	'If you could only have one superpower, what would it be?',
    '123':	'What’s the best thing to do when you’re alone?',
    '124':	'Will you ever imagine having a child named after you?',
    '125':	'Do you want to have a cat as a companion or do you want to be a cat instead?',
    '126':	'What’s one body part that you wouldn’t even mind losing?',
    '127':	'For you, what does a perfect vacation look like?',
    '128':	'Which one do you prefer: being controlled or be in control?',
    '129':	'What are your phobias?',
    '130':	'Do you feel happy to be my friend?',
    '131':	'What makes you jealous?',
    '132':	'Is there someone you really hate?',
    '133':	'Who gave you the best compliment?',
    '134':	'Which film do you want to see turned into a musical?',
    '135':	'Do you still believe in Santa Claus?',
    '136':	'How would you describe your greatest enemy?',
    '137':	'When was the last time you screwed anything up and no one ever noticed?',
    '138':	'Have you already experienced writing a journal?',
    '139':	'What do you usually daydream about?',
    '140':	'If you were given the chance to listen to a singer or a band for the rest of your life, who/what would it be?',
    '141':	'What are the things you wish you could easily forget?',
    '142':	'What’s the most beautiful part of your face?',
    '143':	'Has anyone given you a strange gift?',
    '144':	'What’s the weirdest thing on your bucket list?',
    '145':	'Have you ever pulled out a tooth just to get money from the tooth fairy?',
    '146':	'What are the childish acts you still enjoy doing up until now?',
    '147':	'What does your brain try to make you do and you have to resist yourself not to do it?',
    '148':	'What three things did your past relationship teach you?',
    '149':	'What do you think is the best hangover cure?',
    '150':	'What are the foreign languages you’d like to master?',
    '151':	'n your own opinion, how smart are you?',
    '152':	'When was the last time you’ve ever felt jealous?',
    '153':	'What is the biggest pimple you have ever had?',
    '154':	'Do you still remember the place where we first met?',
    '155':	'Would you move to another country for love?',
    '156':	'When was the time you felt really proud of me?',
    '157':	'What has been your worst nightmare?',
    '158':	'What usually keeps you up at night when you couldn’t sleep?',
    '159':	'Were you born for challenges?',
    '160':	'Are you confident to face the future?',
    '161':	'Who gave you the weirdest gift?',
    '162':	'What makes you cry?',
    '163':	'When was the last time you cried?',
    '164':	'How many concerts have you gone to?',
    '165':	'What would our friendship be called if it was a comedy movie?',
    '166':	'What would you name your car?',
    '167':	'Do you think life after death is really possible?',
    '168':	'What is so special about you?',
    '169':	'What will you tell your past self?',
    '170':	'What movie did you last watch inside the cinema?',
    '171':	'Which one do you prefer: summer or winter?',
    '172':	'Do you believe in aliens?',
    '173':	'What was the best year of your life?',
    '174':	'Do you actually believe in soulmates?',
    '175':	'What is your biggest accomplishment in life?',
    '176':	'What TV series could you watch several times?',
    '177':	'Where do you like to go right now?',
    '178':	'Where’s the worst-smelling place you have ever been?',
    '179':	'Will you be willing to move to another country without your friends and family?',
    '180':	'What qualities do you want in a partner who will be with you for the rest of your life?', 
    '181':	'If you were given the chance to travel back to the past, where would you go?',
    '182':	'What do you usually eat for breakfast?',
    '183':	'Which store would you like if you could just shop at one for the rest of your life?',
    '184':	'What household chore do you hate doing the most?',
    '185':	'Who is your role model in life?',
    '186':	'Do you really care about the Academy Awards, or do you think they’re just dumb?',
    '187':	'Who you share the last slice of cake with if there was just one piece left at your birthday party?',
    '188':	'Which celebrity would you rate as a perfect 10?',
    '189':	'What music do you usually play on a road trip?',
    '190':	'What are the things that drive you crazy?',
    '191':	'What syrup do you like with your pancake: honey or chocolate?',
    '192':	'Do you plan to have kids?',
    '193':	'What is your most favorite holiday?',
    '194':	'What are the things I do that you wish I would stop doing?',
    '195':	'What’s the first book you’ve read?',
    '196':	'What are the facts about you that you think I would find difficult to believe?',
    '197':	'Which body part is your favorite?',
    '198':	'What has been the worst phase in your life?',
    '199':	'What do you prioritize more: relationship or career?',
    '200':	'What flower is your favorite?',
    '201':	'What are your hidden talents?',
    '202':	'What’s your most favorite family tradition?',
    '203':	'Have you ever been caught while sneaking outside the house?',
    '204':	'What’s the meaning of your name?',
    '205':	'Do you ever dream of living somewhere else?',
    '206':	'What is/was your favorite subject in school?',
    '207':	'What are your hopes for the future?',
    '208':	'What usually scares you the most?',
    '209':	'What’s the weirdest animal for you?',
    '210':	'What will be your reaction if you see a ghost?', 
    '211':	'If you were a bird, what kind of bird would you be?',
    '212':	'Does my face look funny to you?',
    '213':	'Who was your first crush?',
    '214':	'What are you actually good at?',
    '215':	'Do you hate math?',
    '216':	'What’s your favorite lullaby?',
    '217':	'What was your reaction when you found out you were going to be parents for the first time?',
    '218':	'What is your dream for me?',
    '219':	'What would you serve if you were to make a special dinner for the family?',
    '220':	'What are the things you love the most about yourself?',
    '221':	'Can you guess what I’m thinking right now?',
    '222':	'What’s your greatest philosophy in life?',
    '223':	'What is the worst decision you’ve ever made?',
    '224':	'Where did all of our family traditions originate?',
    '225':	'What is your favorite day of the week?',
    '226':	'Where did you tie the knot?',
    '227':	'What’s the weirdest Halloween costume you have ever worn in your entire life?',
    '228':	'What do you miss the most about being a kid?',
    '229':	'How do you inspire other people?',
    '230':	'What is the best song to describe your life right now?',
    '231':	'Where do you see yourself in the next 5 years?',
    '232':	'Have you ever stolen food from the refrigerator and blamed it on someone?',
    '233':	'What do you hate about me?',
    '234':	'What’s your favorite car brand?',
    '235':	'What would you do if you knew you would be good in a different profession?',
    '236':	'Do you like to exercise regularly?',
    '237':	'What’s the worst food you’ve ever eaten?',
    '238':	'What is your most cherished possession?',
    '239':	'What’s the most valuable thing you’ve learned in life?',
    '240':	'What makes you really angry?',
    '241':	'If you were a pair of shoes, what brand would you like to be?',
    '242':	'What’s your dream job?',
    '243':	'What habits of other people you definitely find disgusting?',
    '244':	'Do you still keep secrets from mom/dad?',
    '245':	'What’s the extreme challenge in your life that you’ve already overcome?',
    '246':	'Have you ever thought of having plastic surgery?',
    '247':	'What sound do you hate?',
    '248':	'What is your current favorite TV show?',
    '249':	'Which of the Seven Dwarfs resembles you the most?',
    '250':	'Without calling 911 when you are in danger, what would you do instead?',
    '251':	'What is your favorite dance move when you were a kid?',
    '252':	'If you were given the chance to kiss and hug someone, who would that be?',
    '253':	'What is the worst punishment your parents gave you?',
    '254':	'How many countries have you visited so far?',
    '255':	'Have you experienced falling down the stairs?',
    '256':	'What are the challenges you never gave up on?',
    '257':	'What is one piece of advice you wished you’ve seriously taken?',
    '258':	'What do you like most about going to the beach?',
    '259':	'Have you experienced being confined in a hospital?',
    '260':	'If you are drowning, who do you think would save your life?',
    '261':	'What is the most embarrassing moment you had in your workplace?',
    '262':	'Who has taught you the best lesson in life?',
    '263':	'How would it feel like to cry underwater?',
    '264':	'How many times have you traveled by sea?',
    '265':	'Who would you want to portray your life story in a movie?',
    '266':	'Have you ever composed a song?',
    '267':	'What’s the last thing on your bucket list?',
    '268':	'How was your wedding?',
    '269':	'Which fictional book character would like to meet in the future?',
    '270':	'Has anyone tried to kill you?',
    '271':	'Who eats the most in the family?',
    '272':	'Who is your childhood best friend?',
    '273':	'Do you get thirsty in the middle of the night?',
    '274':	'What are the qualities you search for in other people?',
    '275':	'Do you think fish ever get thirsty?',
    '276':	'Which of the politicians would you like to marry?',
    '277':	'How competitive are you?',
    '278':	'What family traditions have we forgotten about that you would like to revive?',
    '279':	'If you could be part of another family, whose family would it be?',
    '280':	'Who is your favorite athlete?',
    '281':	'What is your favorite sports team?',
    '282':	'What are the musical instruments you can play?',
    '283':	'What would you do if you become lost in a city you aren’t familiar with?',
    '284':	'How old were you when you were allowed to have a cellphone?',
    '285':	'Can you name 5 things that are hidden inside your bedroom?',
    '286':	'Do you feel any pressure right now?',
    '287':	'If you could make one word famous, what would it be?',
    '288':	'What movie are you going to make if you become a filmmaker?',
    '289':	'What is your dream laptop?',
    '290':	'How long was your last relationship with your boyfriend/girlfriend?',
    '291':	'Which member of your family were you closest to as a child?',
    '292':	'If you could be great in only one sport, which sport would you choose?',
    '293':	'Do you see yourself as creative?',
    '294':	'Do you know how to change a flat tire?',
    '295':	'If you were ever bullied as a child, what did you do about it?',
    '296':	'What would you do if ever we were given a special time together?',
    '297':	'What type of genre would you choose if you were an author?',
    '298':	'What time were you born?',
    '299':	'Who do you not trust among your friends?',
    '300':	'Are you an impulsive type of person?',
    '301':	'Do you keep a really big secret from someone/anyone?',
    '302':	'Who is your favorite superhero?',
    '303':	'What are the things you’d bring in a zombie apocalypse?',
    '304':	'If you could teach a dog one trick, what would it be?',
    '305':	'Do you watch the full ad on YouTube or you just skip them?',
    '306':	'If someone would let you borrow their car, where would you go?',
    '307':	'Who do you think is your celebrity look-a-like?',
    '308':	'Why does it still rain in the movies when there is a funeral and then stop right after the burial?',
    '309':	'What flower would you prefer if you awoke as a flower one day?',
    '310':	'What location would you choose if you had the power to make it disappear?',
    '311':	'Where would you rather be: a place with no food but has water or with food but has no water?',
    '312':	'What’s the last food you ate?',
    '313':	'What was something you really wanted to do as a kid but never had the opportunity to do?',
    '314':	'Do you know any funny pick-up lines?',
    '315':	'Is there something you recently regret doing?',
    '316':	'What’s your least favorite board game?',
    '317':	'When you reach the age of 80, what will matter the most to you?',
    '318':	'Have you ever been caught staring at the opposite gender?',
    '319':	'Would you like to be famous someday?',
    '320':	'What are your top 5 favorite fast-food restaurants?',
    '321':	'Which brand of smartphone do you dislike the most?',
    '322':	'Have you ever had to run from the police?',
    '323':	'What law would you like to make that every person should strictly follow?',
    '324':	'Would you rather be a hero or a villain in a movie?',
    '325':	'What’s that certain thing that people always misunderstand about you?',
    '326':	'If you survived a plane crash, what would you do next?',
    '327':	'Do you like dipping your Oreo in milk?',
    '328':	'Are you a collector of something?',
    '329':	'What do you think God looks like?',
    '330':	'Would you rather wear shoes or slippers?',
    '331':	'What’s your lucky number?',
    '332':	'Have you recently checked out one of your bucket lists?',
    '333':	'Do you like to stalk someone on social media?',
    '334':	'Are you smart enough to solve 100 addition problems in 100 minutes?',
    '335':	'What is your most-used emoji?',
    '336':	'If you could sit on a bench in the middle of a beautiful forest, who would you like to sit next to you and why?',
    '337':	'What fruit would you be if you were a fruit?',
    '338':	'When the doctor says, "You have 24 hours to live," what will you do with the time you have left?',
    '339':	'Have you ever taken anything out of your possession and failed to return it?',
    '340':	'Do you ever believe in heroic deeds?',
    '341':	'What is the highest degree of pain you have ever experienced on a scale of 1-10?',
    '342':	'When you see a homeless person, what is your first thought?',
    '343':	'Have you ever dropped something on the floor, then picked it up and ate it?',
    '344':	'What is your favorite indoor activity?',
    '345':	'What is your favorite outdoor activity?',
    '346':	'Do you get bored easily?',
    '347':	'If you could choose one imaginary friend, who is it going to be?',
    '348':	'What age would you prefer if you could choose any age for the rest of your life, and why?',
    '349':	'Where would you go if you could teleport yourself from one place to another?',
    '350':	'Are you afraid of going near robots?',
    '351':	'Which one do you like: foot massage or hand massage?',
    '352':	'How many pizzas can you eat in a minute?',
    '353':	'What is a popular food ingredient, spice, or herb that you dislike?',
    '354':	'What are the things that take up too much of your time?',
    '355':	'Did you ever think that clowns were creepy?',
    '356':	'What would you do for an extra hour if you had 25 hours in a day?',
    '357':	'Would you choose to live for another 100 years or start over from the beginning?',
    '358':	'What do you want me to tell you?',
    '359':	'What’s your favorite sandwich spread?',
    '360':	'Are you more of a "fix it yourself" or "call an expert" kind of person?',
    '361':	'What time do you usually sleep?',
    '362':	'What time do you usually wake up?',
    '363':	'How many pairs of shoes do you have?',
    '364':	'Would you rather visit your ancestors in the past or meet your descendants in the future?',
    '365':	'Do you think you would enjoy a love-hate relationship with someone?',
    '366':	'Do you spend too much time playing games on your smartphone?',
    '367':	'What three things would you want with you if you were stranded on a desert island?',
    '368':	'Did you ever think you had superpowers as a child?',
    '369':	'Would you spend a thousand dollars on food?',
    '370':	'Which toy do you wish didn’t exist?',
    '371':	'Which year would you visit if you could travel back in time 1,000 years?',
    '372':	'What did you learn today?',
    '373':	'What has been the longest time you had to wait for someone?',
    '374':	'What season best fits your personality?',
    '375':	'What’s your opinion on garden gnomes or pink flamingos?',
    '376':	'What would you teach every girl on the planet about men if you had the chance?',
    '377':	'What has been the longest plane trip you’ve ever taken?',
    '378':	'What vegetable would you be if you were a vegetable?',
    '379':	'Would you like to tell me a story?',
    '380':	'Do you want to change the world?',
    '381':	'What’s a current habit that you want to quit?',
    '382':	'Does Christmas mean something special to you?',
    '383':	'What is your favorite Winter Olympics sport?',
    '384':	'What has been the most severe weather you’ve ever experienced?',
    '385':	'What habits are preventing you from achieving your goals?',
    '386':	'How do your friends usually describe you?',
    '387':	'When no one is around, what do you like to wear?',
    '388':	'What did you buy recently?',
    '389':	'Could you describe your favorite material object that you already have?',
    '390':	'What kind of company would you start if I offered you $50,000 to start one?',
    '391':	'What words of advice would you offer to your younger self?',
    '392':	'For a day, would you rather be a hobbit or an elf?',
    '393':	'What was your favorite childhood snack?',
    '394':	'What’s your favorite day of the week?',
    '395':	'What’s your favorite month?',
    '396':	'Who was your favorite classmate?',
    '397':	'Do I look attractive to you?',
    '398':	'Which of the continents have you already been to?',
    '399':	'What style of design do you think is the perfect match for you when it comes to houses?',
    '400':	'Have you ever walked out of the cinema without finishing the movie?',
    }; 
    //Object will 400 questions
    
    let askedList = []; //Array that will have the questions that were already asked
    var phrase =""; //variable that will get the string for the question
    
    // Function to generate a random number to choose a question
    function generateRandom(maxLimit = 401){
      let rand = Math.random() * maxLimit;
      rand = Math.floor(rand);
      //this line prevents the zero value
      if (rand == 0){generateRandom(maxLimit = 401);}
      return rand;
    }; 
    
    //Function to displays the question into the first div and puts the questions inside the used questions.
    function getQ(){
      let randomNumber = generateRandom(maxLimit = 401);
      //this line prevents a duplicate question
      if (askedList.includes(qList[randomNumber])){
        getQ();
      } 
      phrase = qList[randomNumber];
      return document.getElementById("newQ").innerHTML = phrase;
    }; 
    
    //Function to displays the question into the second div as used question.
    function addQ(){
      askedList.push(phrase);
      askedList.push("<br>");
     return document.getElementById("askedQ").innerHTML = askedList; 
    }; 
    
    //event that trigers the JS code
    document.getElementById("btnx").onclick = function() { getQ(),addQ() };